In [67]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

Data dictionary
Species        category
SepalLength       Int64
SepalWidth        Int64
PetalLength       Int64
PetalWidth        Int64

In [76]:

file_path='/home/elcaskerito/Documents/Stevens Jupiter/new/ml_eda_AI_stevens_institute_tech/learning/hepatitis_C2.csv'

# # Read CSV file with appropriate handling of missing values
df = pd.read_csv(file_path, na_values='?')


print(df.describe())

df.head(30)

             Row      Class        AGE  LIVER_FIRM  BILIRUBIN    ALBUMIN
count  30.000000  30.000000  30.000000   30.000000  30.000000  30.000000
mean   15.500000   1.533333  43.766667    1.500000   1.516667   3.633333
std     8.803408   0.507416  12.623687    0.508548   1.213738   0.700410
min     1.000000   1.000000  22.000000    1.000000   0.400000   2.100000
25%     8.250000   1.000000  37.250000    1.000000   0.700000   3.150000
50%    15.500000   2.000000  41.500000    1.500000   1.000000   3.800000
75%    22.750000   2.000000  50.000000    2.000000   1.925000   4.175000
max    30.000000   2.000000  78.000000    2.000000   4.800000   4.900000

    Row  Class  AGE  LIVER_FIRM  BILIRUBIN  ALBUMIN
0     1      2   38           1        0.7      4.2
1     2      1   47           1        1.0      2.6
2     3      1   47           1        1.7      2.1
3     4      2   38           2        0.7      4.1
4     5      1   48           1        4.8      2.7
5     6      1   42           2        0.5      3.8
6     7      1   41           1        4.2      3.4
7     8      1   38           1        0.4      3.8
8     9      2   34           2        0.9      4.0
9    10      1   33           2        0.7      3.0
10   11      1   50           1        2.8      2.4
11   12      2   38           2        2.0      2.9
12   13      2   27           2        0.8      3.8
13   14      2   78           2        0.7      4.0
14   15      2   40           1        0.6      4.0
15   16      2   30           1        2.2      4.9
16   17      1   43           2        1.2      3.1
17   18      2   50           2        0.9      3.5
18   19      2   25           2        0.4      4.3
19   20      1   58           1        2.0      3.3
20   21      1   59           1        1.5      3.6
21   22      1   57           2        4.6      3.3
22   23      2   42           2        0.9      4.7
23   24      2   39           1        1.3      4.4
24   25      2   58           1        1.4      2.7
25   26      2   32           1        1.0      3.7
26   27      1   56           1        2.9      4.0
27   28      2   66           2        1.2      4.3
28   29      1   37           2        0.6      4.2
29   30      2   22           2        0.9      4.2

In [69]:
df.dtypes

Row             int64
Class           int64
AGE             int64
LIVER_FIRM      int64
BILIRUBIN     float64
ALBUMIN       float64
dtype: object

In [77]:


attr = df.drop(columns = ['Row']) 
target = attr['Class']

trainSet = attr.drop(columns = ['Class']) 



print(trainSet)



print('\n--------------------------------------- *test set start here*-------------------------- \n')



print(target.head(5))
# df.head(10)
# print(testSet)

    AGE  LIVER_FIRM  BILIRUBIN  ALBUMIN
0    38           1        0.7      4.2
1    47           1        1.0      2.6
2    47           1        1.7      2.1
3    38           2        0.7      4.1
4    48           1        4.8      2.7
5    42           2        0.5      3.8
6    41           1        4.2      3.4
7    38           1        0.4      3.8
8    34           2        0.9      4.0
9    33           2        0.7      3.0
10   50           1        2.8      2.4
11   38           2        2.0      2.9
12   27           2        0.8      3.8
13   78           2        0.7      4.0
14   40           1        0.6      4.0
15   30           1        2.2      4.9
16   43           2        1.2      3.1
17   50           2        0.9      3.5
18   25           2        0.4      4.3
19   58           1        2.0      3.3
20   59           1        1.5      3.6
21   57           2        4.6      3.3
22   42           2        0.9      4.7
23   39           1        1.3      4.4
24   58           1        1.4      2.7
25   32           1        1.0      3.7
26   56           1        2.9      4.0
27   66           2        1.2      4.3
28   37           2        0.6      4.2
29   22           2        0.9      4.2

--------------------------------------- *test set start here*--------------------------

0    2
1    1
2    1
3    2
4    1
Name: Class, dtype: int64

In [71]:
from sklearn.preprocessing import MinMaxScaler
# Initialize MinMaxScaler
scaler = MinMaxScaler()
# Fit and transform the data
trainSet = pd.DataFrame(scaler.fit_transform(trainSet), columns=trainSet.columns)

print('\n--------------------------------------- *Scalling the data*-------------------------- \n')
trainSet.head()

--------------------------------------- *Scalling the data*--------------------------

        AGE  LIVER_FIRM  BILIRUBIN   ALBUMIN
0  0.285714         0.0   0.068182  0.750000
1  0.446429         0.0   0.136364  0.178571
2  0.446429         0.0   0.295455  0.000000
3  0.285714         1.0   0.068182  0.714286
4  0.464286         0.0   1.000000  0.214286

In [ ]:

train_trainSet,test_trainSet, train_testSet, test_testSet = train_test_split(trainSet, target,test_size = 0.16, random_state = 13, shuffle = True)

In [145]:
# from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
k_values = [1,2,3]


for k in k_values:
    knn = KNeighborsClassifier(n_neighbors = k)
#     knn = KNeighborsClassifier(n_neighbors = k,weights='distance')
    knn.fit(train_trainSet, train_testSet)
    target_pred = knn.predict(test_trainSet)
#     accuracy = round(np.mean(target_test==target_pred ) * 100, 2)
    accuracy = accuracy_score(test_testSet,target_pred ) 
    print(f'Accuracy of model with k = {k}: {accuracy}')
    print('')

Accuracy of model with k = 1: 0.6

Accuracy of model with k = 2: 0.6

Accuracy of model with k = 3: 0.6

In [137]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(test_testSet, target_pred)

print('Confusion Matrix')
print(confusion_matrix(test_testSet, target_pred))
print()
print('Accuracy score')
print(accuracy_score(test_testSet, target_pred))
print()
print('Classification Report')
print(classification_report(test_testSet, target_pred))

Confusion Matrix
[[0 1]
 [0 4]]

Accuracy score
0.8

Classification Report
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.80      1.00      0.89         4

    accuracy                           0.80         5
   macro avg       0.40      0.50      0.44         5
weighted avg       0.64      0.80      0.71         5

/home/elcaskerito/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/elcaskerito/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/elcaskerito/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))